# Generated by Django 4.1.7 on 2023-02-20 20:29

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=150)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='profile_pics/no-profile-pic.png', upload_to='static/profile_pics/')),
                ('full_name', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('program', models.CharField(choices=[('01', 'BTech'), ('41', 'MTech'), ('61', 'PhD'), ('21', 'MSc'), ('43', 'MS-R'), ('22', 'MA'), ('02', 'BDes'), ('42', 'MDes'), ('00', 'Error')], max_length=2)),
                ('department', models.CharField(choices=[('01', 'Computer Science & Engineering'), ('02', 'Electronics & Communication Engineering'), ('03', 'Mechanical Engineering'), ('04', 'Civil Engineering'), ('54', 'Centre for Rural Technology'), ('05', 'Design'), ('61', 'Data Science'), ('63', 'E-Mobility'), ('06', 'Biosciences & Bioengineering'), ('07', 'Chemical Engineering'), ('22', 'Chemical Science & Technology'), ('08', 'Electronics & Electrical Engineering'), ('23', 'Mathematics & Computing'), ('21', 'Engineering Physics'), ('41', 'Humanities & Social Sciences'), ('51', 'Centre for Energy'), ('52', 'Centre for Environment'), ('53', 'Centre for Nanotechnology'), ('55', 'Centre for Linguistic Science & Technology'), ('00', 'Error')], max_length=3)),
                ('bio', models.TextField(max_length=500)),
                ('graduating', models.BooleanField(default=False)),
                ('address', models.CharField(default='', max_length=500)),
                ('gmailid', models.CharField(default='', max_length=60)),
                ('phoneno', models.CharField(default='', max_length=10, validators=[core.models.Profile.only_int])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('profile_pic', models.ImageField(default='team/no-profile-pic.png', upload_to='team/')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=400)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to='core.profile')),
                ('given_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=300)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profilequestion')),
            ],
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_to', to='core.profile')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pollquestion')),
                ('voted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('cnt_0', models.IntegerField(default=0)),
                ('cnt_1', models.IntegerField(default=0)),
                ('cnt_2', models.IntegerField(default=0)),
                ('cnt_3', models.IntegerField(default=0)),
                ('cnt_4', models.IntegerField(default=0)),
                ('cnt_5', models.IntegerField(default=0)),
                ('cnt_6', models.IntegerField(default=0)),
                ('cnt_7', models.IntegerField(default=0)),
                ('cnt_8', models.IntegerField(default=0)),
                ('cnt_9', models.IntegerField(default=0)),
                ('profile_0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_0', to='core.profile')),
                ('profile_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_1', to='core.profile')),
                ('profile_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_2', to='core.profile')),
                ('profile_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_3', to='core.profile')),
                ('profile_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_4', to='core.profile')),
                ('profile_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_5', to='core.profile')),
                ('profile_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_6', to='core.profile')),
                ('profile_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_7', to='core.profile')),
                ('profile_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_8', to='core.profile')),
                ('profile_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_9', to='core.profile')),
            ],
        ),
    ]
